name: "test"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master

jobs:
  # This job creates a real release for the action itself:
  # https://sentry-ecosystem.sentry.io/releases/?project=6576594
  create-a-release-on-push:
    name: "Test current action"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Tweak this step to test various scenarios
    - name: Sentry Release
      uses: getsentry/action-release@v1 # Change the version for testing
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_LOG_LEVEL: debug
      with:
        projects: action-release
        ignore_missing: true

  mock-release: # Make sure that the action works on a clean machine without building
    name: "Build image & mock a release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: './.github/actions/use-local-dockerfile'

    - name: Mock creating a Sentry release
      uses: ./
      env:
        MOCK: true
      with:
        environment: production

  mock-release-working-directory:
    name: "Build image & mock a release in a different working directory"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory we'll be running from
      uses: actions/checkout@v3
      with:
        path: main/

    - name: Checkout directory we'll be testing
      uses: actions/checkout@v3
      with:
        path: test/

    - uses: './main/.github/actions/use-local-dockerfile'
      with:
        working_directory: main

    - name: Mock creating a Sentry release in a different directory
      uses: ./main
      env:
        MOCK: true
      with:
        environment: production
        working_directory: ./test
