name: "integration tests"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
env:
  # Variables defined in the repository
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  # For PRs, we post to a different project since you can't have different commits based on environments
  # https://sentry-ecosystem.sentry.io/releases/?project=4505075304693760
  # XXX: We need to define different variables in the repo based if we're running for a PR or the master branch
  SENTRY_PROJECT: action-release-prs

jobs:
  # You're welcome to make changes on this job as part of your PR in ourder to test out your changes
  # We can always undo the changes once we're satisfied with the results
  #
  # Uncomment and tweak the commented out step
  #
  # Secrets and variables on this repo do not get shared with PRs openeed on a fork, thus,
  # add SENTRY_ORG and SENTRY_PROJECT as variables to your fork and SENTRY_AUTH_TOKEN as a secret
  # if you want to use this job. Checkout the README.md in how to create the internal integration
  create-real-release-per-push:
    name: "Test current action"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Because PRs always do a merge with the default branch
        # This supports creating a release using the commits from the branch
        ref: ${{ github.event.pull_request.head.sha }}

    # This allows executing the action's code in the next step rather than a specific tag
    - uses: './.github/actions/use-local-dockerfile'

    # If you want this step to be mocked you can add "MOCK: true" to the env
    - name: Create a staging release
      # XXX: This step will fail for forks, skip step on forks and let contributors tweak it when ready
      if: github.ref != 'refs/heads/master'
      uses: ./
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_LOG_LEVEL: debug
      with:
        ignore_missing: true

  mock-release: # Make sure that the action works on a clean machine without building Docker
    name: "Build image & mock a release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: './.github/actions/use-local-dockerfile'

    - name: Mock creating a Sentry release
      uses: ./
      env:
        MOCK: true
      with:
        environment: production

  mock-release-working-directory:
    name: "Build image & mock a release in a different working directory"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory we'll be running from
      uses: actions/checkout@v3
      with:
        path: main/

    - name: Checkout directory we'll be testing
      uses: actions/checkout@v3
      with:
        path: test/

    - uses: './main/.github/actions/use-local-dockerfile'
      with:
        working_directory: main

    - name: Mock creating a Sentry release in a different directory
      uses: ./main
      env:
        MOCK: true
      with:
        environment: production
        working_directory: ./test
